codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 60..90

# Status checks
status:
  project:
    default:
      threshold: 1%
      target: 75%
  patch:
    default:
      threshold: 1%

flags:
  backend:
    paths:
      - backend/src
    carryforward: true

ignore:
  - "**/test/**"
  - "backend/src/index_old.js"
