import mongoose from 'mongoose';

const FeedbackSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true },
    rating: { type: Number, enum: [-1, 0, 1], required: true },
    ratingLabel: {
      type: String,
      enum: ['pertinent', 'moyen', 'hors_sujet'],
      default: function defaultRatingLabel() {
        if (this.rating === 1) return 'pertinent';
        if (this.rating === 0) return 'moyen';
        return 'hors_sujet';
      },
    },
    reason: { type: String, default: '', trim: true, maxlength: 240 },
    metadata: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { timestamps: true }
);

const ChallengeSchema = new mongoose.Schema(
  {
    userId: { type: String, required: true },
    userName: { type: String, default: 'Anonyme' },
    content: { type: String, required: true, trim: true, maxlength: 2000 },
  },
  { timestamps: true }
);

/**
 * RoomMessage — a single message in a salon.
 *
 * senderId  : userId for human senders, 'ai' for the AI colleague
 * isAI      : true when the message was generated by Gemini
 * type      : 'text' for chat, 'document' when AI produces a structured deliverable
 * challenges: list of comments/challenges on a document message
 */
const RoomMessageSchema = new mongoose.Schema(
  {
    roomId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Room',
      required: true,
      index: true,
    },
    senderId: { type: String, required: true },    // userId or 'ai'
    senderName: { type: String, required: true },   // displayName or 'IA'
    isAI: { type: Boolean, default: false },
    content: { type: String, required: true, trim: true },
    // Message shape used by Channels: text, AI reply, artifact, research, decision or system
    type: {
      type: String,
      enum: ['text', 'ai', 'artifact', 'research', 'decision', 'system', 'document'],
      default: 'text',
    },
    documentTitle: { type: String, trim: true, maxlength: 200 },
    // Comments / challenges on a document, added by any member
    challenges: { type: [ChallengeSchema], default: [] },
    data: { type: mongoose.Schema.Types.Mixed, default: {} },
    // Thumbs up/down feedback on AI messages (one per userId)
    feedback: { type: [FeedbackSchema], default: [] },
  },
  { timestamps: true }
);

export default mongoose.model('RoomMessage', RoomMessageSchema);
