// Mocks generated by Mockito 5.4.4 from annotations
// in hackit_mvp_flutter/test/data/repositories/video_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i7;
import 'package:hackit_mvp_flutter/core/network/network_info.dart' as _i6;
import 'package:hackit_mvp_flutter/data/cache/cache_manager.dart' as _i5;
import 'package:hackit_mvp_flutter/services/api_service.dart' as _i3;
import 'package:hackit_mvp_flutter/shared/domain/models/video.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchResult_0 extends _i1.SmartFake implements _i2.SearchResult {
  _FakeSearchResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideo_1 extends _i1.SmartFake implements _i2.Video {
  _FakeVideo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SearchResult> searchVideos(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideos,
          [query],
        ),
        returnValue: _i4.Future<_i2.SearchResult>.value(_FakeSearchResult_0(
          this,
          Invocation.method(
            #searchVideos,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.SearchResult>);

  @override
  _i4.Future<_i2.Video> getVideoDetails(String? videoId) => (super.noSuchMethod(
        Invocation.method(
          #getVideoDetails,
          [videoId],
        ),
        returnValue: _i4.Future<_i2.Video>.value(_FakeVideo_1(
          this,
          Invocation.method(
            #getVideoDetails,
            [videoId],
          ),
        )),
      ) as _i4.Future<_i2.Video>);
}

/// A class which mocks [CacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheManager extends _i1.Mock implements _i5.CacheManager {
  MockCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set videoBox(dynamic _videoBox) => super.noSuchMethod(
        Invocation.setter(
          #videoBox,
          _videoBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set searchResultBox(dynamic _searchResultBox) => super.noSuchMethod(
        Invocation.setter(
          #searchResultBox,
          _searchResultBox,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveVideo(_i2.Video? video) => (super.noSuchMethod(
        Invocation.method(
          #saveVideo,
          [video],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveVideos(List<_i2.Video>? videos) => (super.noSuchMethod(
        Invocation.method(
          #saveVideos,
          [videos],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Video?> getVideo(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getVideo,
          [id],
        ),
        returnValue: _i4.Future<_i2.Video?>.value(),
      ) as _i4.Future<_i2.Video?>);

  @override
  List<_i2.Video> getVideos(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #getVideos,
          [ids],
        ),
        returnValue: <_i2.Video>[],
      ) as List<_i2.Video>);

  @override
  _i4.Future<void> saveSearchResult(_i2.SearchResult? result) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSearchResult,
          [result],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.SearchResult?> getSearchResult(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchResult,
          [query],
        ),
        returnValue: _i4.Future<_i2.SearchResult?>.value(),
      ) as _i4.Future<_i2.SearchResult?>);

  @override
  _i4.Future<void> clearOldCache() => (super.noSuchMethod(
        Invocation.method(
          #clearOldCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<_i7.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i4.Stream<_i7.ConnectivityResult>.empty(),
      ) as _i4.Stream<_i7.ConnectivityResult>);
}
